[gcp_service_account]
type = "service_account"
project_id = "kaspa-analytics"
private_key_id = "33d940140ae154313d78b8a07500443db50cf6ab"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCp0FLMtwDsszCR
c8VGRqsKoPk8tGT/Y8G9ViDxo/QTlNMhK/sYhTfDIoWfxA9UNcgaqfVkvvMPsTk/
j7oYx0pUQqjCC3K/R2FUVGXJtTNOSKYfGaEMT1EjAiwARMA66cpJKqDlQENswvHj
2AcWq4HVYJZfpZmOrFSK+7HcTs/55X5hFu42a4J3JRI1+NrnVo1WldaoJZ0c6HWb
LZeAeEB/VYh0C+Wxovj9G7mzYuij53o/8zcSqw64kHeHB4h/6TY/xx04NgFbNucx
rwK2XFxiPKspV4JQ3qAUvG4de1rwJcjqXLdcRqPsS8IY8acGTCI/e1B5a2ZOO0iO
SEt8fv17AgMBAAECggEABEPxfdHk9I0bCF7w6BnTUbIxwHwZg1llSZULFna9+pXv
kwg7R5DlEdeL+rOJMl4izMSodM41EG0CWUiKGKA84OPxwDoFuQHufcNG8UDwwnkh
rxX3jSBwPcxgADu527ZOo0rY/W6BTbnnKzLHGXiCYN01ub5Q8/FRMv0tKQb+bged
SkDrsqPPpEjHNZ1Qzo08Nz7nQEyhFg92jtB6iQsmO7z45Rob2g6qpiAOE1wCEzy8
TDNUL8ePDrzzTdQbkF5dBPH3UvEC/uAnlPBsOILZhcW5mWZFWr/Tn9/PLZhXcmY5
bz6dJXkBCnqRC4WeXkpMRpWA3jh8giCwIRzp4L+gZQKBgQDucHmu7ysvmLDj3EQ6
ScDulFvtrFaAmHT6rezBqDyCN3RB6SY7iYoGOm/6+bOdfa5fIf380ZCGoYxj4PQo
Ngl76+0zkEKlcABIATBLNnT7zm/IPnpf8fG3cFxK5wX7+cgw5ehG7F7eK5LWqbwD
ZYCG/+X4Fv5N7YIjd0IVpeyyhQKBgQC2Ufv86rGfcbYECqzdLrkjnxZ0ItXeOx5/
/VfZQzKNBtFXOQTgyyZXl02NAB54LxdAI5aq2so1aiLjPameQ5zmkyWu8Dzf45Hj
neIxty/2O+puOlY8uzwWhBesUgXbkxQP3bekxxyaLsoctg3p/H2ijYRrVpCCFem4Y
jN7QrYPv/wKBgA+QfAD1T8Zdmz5khHehlNx+BrovA76FNS2f6NKDXt/JKueahopg
YggiDGk/n3/qUlWXbHLyYxLGvNlQN9/gFyJltiglhJQ0CXCp0zM1rNE7GoThvy9A
Jd0pkny5M+TM20qF13G5wD+UbJNipQk7uPYXAjX9mkAP/uy9viyXlinZAoGAfNH8
Ntdm68Yp2vKEDpmiXuTXtoLy8MaAxxdnQXNj9HEqeRCsakoq4eTQTyw5sAZtYJf8
2tQXhCI56GGa8qNPk/xB3FbVFmLyyk0Jt1HlMjIYtbFm6aEKNYebvdo0z8KiSI+T
C2VQ2mtLaLmO7+FM/i3I9WL8cOW04lHvaeahYXkCgYEAgiUG55sEG5ZrwLjbyZF2
LlhoGHdnaBA3ebUZjr+tv1IiQ9DNijyv8qSARagZNQnSp4dvyp6ZV1N0zA6JJceG
MYTAmQhpvnaolRI9S6VLZ/74tkcPa2rciD4gjbLM75WiYP5P5yaL5S4pvnREFm4y
sIMucqCUqLVnhsay4lEEiBg=
-----END PRIVATE KEY-----"""
client_email = "kaspa-sheets-access@kaspa-analytics.iam.gserviceaccount.com"
client_id = "112181467762583506157"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/kaspa-sheets-access%40kaspa-analytics.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
